const Data=[
    {
        id:"1",
        img:"./Images/food.jpg", 
        title:"Food hall",
        desc:"Foodhall is a responsive Blogger theme highlighting a good design for food blogging that brings many awesome.",
        review: "⭐⭐⭐⭐⭐",
        sale:"100",
        price:"$20",
    }, 
    {
        id:"2",
        img:"./Images/ecolife.jpg",
        title:"EcoLife",
        desc:"Ecolife – Organic Food Responsive Prestashop theme is an amazing Prestashop theme in the latest version of Prestashop 1.7.x.",
        review: "⭐⭐⭐⭐",
        sale:"200",
        price:"$30",
    },
    {
        id:"3",
        img:"./Images/flexi.webp",
        title:"FlexiBlog",
        desc:"FlexiBlog is a fully functional multi-purpose blog theme powered by React and Gatsby JS v3 and packed with various page layouts.",
        review: "⭐⭐⭐⭐",
        sale:"2",
        price:"$26",
    },
    {
        id:"4",
        img:"./Images/q.jpg",
        title:"Quarter – Real Estate",
        desc:"Quarter is a Real Estate, Architecture & interior design Bootstrap 5 HTML Template for real estate website.",
        review: "⭐⭐⭐⭐⭐",
        sale:"34",
        price:"$14",
    },
    {
        id:"5",
        img:"./Images/n.png",
        title:"Architeck - Construction",
        desc:"Architeck is a clean and powerful HTML5 Construction and real estate Template fabricated for building & construction companies.",
        review: "⭐⭐⭐",
        sale:"78",
        price:"$29",
    },
    {
        id:"6",
        img:"./Images/p.jpg",
        title:"Realtor - Real Estate",
        desc:"Realtor is a Real Estate, Architecture & interior design Bootstrap 5 HTML Template for real estate website.",
        review: "⭐⭐⭐⭐",
        sale:"65",
        price:"$10", 
    },
];
export default Data;